config/routes.rb
Rails.application.routes.draw do

  root :to => "entries#index"

  match 'feed' => 'feed#index', :format => :xml, :as => 'feed'
  match 'feed/atom.xml' => 'feed#index'

  resources :entries do
    resources :comments
  end

  namespace :admin do
    root :to => 'entries#index'
    resource :settings
    resources :entries
  end

  devise_for :admin, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout'
  }

  match "/:year/:month/:day/:id" => 'entries#show',
    :constraints => {
      :year => /\d{4}/,
      :month => /\d{1,2}/,
      :day => /\d{1,2}/
    }
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  if defined?(Gravtastic)
    include Gravtastic
    gravtastic :size => 64
  end

  attr_accessor :nickname

  belongs_to :entry
  default_scope :order => 'created_at ASC'

  before_validation :bot_check
  validates_presence_of :name, :email, :body, :message => 'Required'

  acts_as_textiled :body

  def send_notification(request)
    begin
      CommentMailer.notification(self, request).deliver
    rescue => e
      logger.error "#{e}\n#{e.backtrace.join("\n")}"
    end
  end

  private

    def bot_check
      unless self.nickname.blank?
        errors.add(:nickname, 'You shouldn\'t have seen this...')
        false
      end
    end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_save :set_published_at

  has_many :comments
  has_friendly_id :title, :use_slug => true
  acts_as_textiled :body

  default_scope :order => 'published_at DESC'
  scope :drafts, :conditions => { :draft => true }
  scope :published, :conditions => { :draft => false }

  private

    def set_published_at
      self.published_at = Time.now unless draft? || self.published_at
    end
end

app/models/settings.rb
class Settings < ActiveRecord::Base

  def do_updates
    Time.zone = self.time_zone
    ActionMailer::Base.default_url_options[:host] = self.host_name
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < Admin::BaseController
  helper_method :entry
  before_filter :set_is_draft, :only => [:create, :update]

  def index
    @drafts  = Entry.drafts
    @published = Entry.published
  end

  def create
    if entry.save
      redirect_to(admin_entries_path, :notice => message)
    else
      render :new
    end
  end

  def update
    if entry.update_attributes(params[:entry])
      redirect_to(admin_entries_path, :notice => message)
    else
      render :edit
    end
  end

  def destroy
    entry.destroy
    redirect_to admin_entries_path
  end

  private

    def entry
      @entry ||= params[:id].blank? ?
        Entry.new(params[:entry]) :
        Entry.find(params[:id])
    end

    def set_is_draft
      params[:entry][:draft] = (params[:commit] =~ /draft/i).present?
    end

    def message
      entry.draft ? "Entry was saved as a draft." : "Entry was published."
    end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

  def update
    if SETTINGS.update_attributes(params[:settings])
      SETTINGS.do_updates
      redirect_to admin_root_path, :notice => 'Settings updated.'
    else
      render :edit
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < Admin::BaseController
  layout 'application'
  skip_before_filter :authenticate_admin!, :only => [ :create, :new ]
  helper_method :entry, :comment

  def create
    if comment.save
      comment.send_notification(request)
      redirect_to entry_path(entry), :notice => 'Your comment was submitted.'
    else
      flash[:error] = 'Unable to submit your comment.'
      render 'entries/show'
    end
  end

  def destroy
    comment.destroy
    redirect_to entry_path(entry), :notice => 'Comment was deleted.'
  end

  private

    def entry
      @entry ||= Entry.find(params[:entry_id])
    end

    def comment
      @comment ||= params[:id].blank? ?
        entry.comments.new(params[:comment]) :
        Comment.find(params[:id])
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include JabeHelper

  before_filter :ensure_current_post_url, :only => :show
  helper_method :entry, :comment

  def index
    @entries = Entry.published.paginate(
      :page => (params[:page] || 1),
      :per_page => (SETTINGS.entries_per_page || 5)
    )
  end

  def show
    if entry.draft? && ! admin_signed_in?
      render 'public/404.html', :layout => false, :status => 404
    end
  end

  private

    def entry
      @entry ||= Entry.find(params[:id])
    end

    def comment
      @comment ||= entry.comments.new
    end

    def ensure_current_post_url
      redirect_to public_entry_path(entry),
        :status => :moved_permanently unless entry.friendly_id_status.best?
    end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    @entries = Entry.published.paginate(
      :page => (params[:page] || 1),
      :per_page => (SETTINGS.entries_per_page || 5)
    )
  end
end

app/helpers/jabe_helper.rb
module JabeHelper
  def public_entry_path(entry)
    "/#{entry.published_at.in_time_zone.to_s(:url_part)}/#{entry.to_param}"
  end

  def public_entry_url(entry)
    "#{SETTINGS.site_url}#{public_entry_path(entry)}"
  end

  def default_gravatar_url
    "#{request.protocol}#{request.host_with_port}/images/gravatar.gif"
  end

  def page_title(title)
    @page_title = title
  end

  def stylesheet(name)
    content_for :stylesheets do
      stylesheet_link_tag(name)
    end
  end

  def javascript(name)
    content_for :javascripts do
      javascript_include_tag(name)
    end
  end
end

app/views/admin/entries/_form.html.haml
= semantic_form_for [:admin, entry] do |form|
  = form.input :title
  = form.input :body
  = form.input :published_at if entry.published_at
  = form.submit 'Save as draft'
  = form.submit 'Publish'

app/views/admin/entries/edit.html.haml
= render 'form'

app/views/admin/entries/index.html.haml
%p
  = link_to 'Start a new entry', new_admin_entry_path
%br

%h2 Drafts

- if @drafts.any?
  %table.entries
    - @drafts.each do |entry|
      %tr
        %td
          = link_to image_tag('delete_page.png'),
            admin_entry_path(entry),
            :confirm => 'Are you sure?',
            :method => :delete,
            :title => 'Delete'
          = link_to image_tag('full_page.png'),
            entry_path(entry),
            :title => 'Preview'
        %td
          = link_to entry.title, edit_admin_entry_path(entry)

%br

%h2 Published

- if @published.any?
  %table.entries
    - @published.each do |entry|
      %tr
        %td.icons
          = link_to image_tag('delete_page.png'),
            admin_entry_path(entry),
            :confirm => 'Are you sure?',
            :method => :delete,
            :title => 'Delete'
          = link_to image_tag('full_page.png'),
            public_entry_path(entry),
            :title => 'Preview'
        %td
          = link_to entry.title, edit_admin_entry_path(entry)
          .when
            = entry.published_at.to_s(:long)

app/views/admin/entries/new.html.haml
= render 'form'

app/views/admin/settings/edit.html.haml
%h2 Site Settings
= semantic_form_for SETTINGS, :url => admin_settings_path do |form|
  = form.input :host_name, :label => 'Domain and port', :hint => '(e.g. pixels-and-bits.com or localhost:3000)'
  = form.input :site_name
  = form.input :tagline
  = form.input :time_zone, :label => 'Your local time zone'
  = form.input :entries_per_page, :label => 'Entries on the home page'
  = form.input :sidebar_heading
  = form.input :github_username
  = form.input :show_github_badge
  = form.input :twitter_username
  = form.input :facebook_url
  = form.input :google_tracker_id
  = form.submit 'Save'

app/views/entries/index.html.haml
#entries
  - @entries.each do |entry|
    .entry{ :class => entry == @entries.last ? 'last' : '' }
      .title
        %h1
          = link_to entry.title, public_entry_path(entry)
      .date
        = entry.published_at.to_s(:long)
      .content
        ~ entry.body.html_safe
      .meta
        = link_to "Comments: #{entry.comments.count}", public_entry_path(entry) + '#comments'
  #pagination.apple_pagination
    = will_paginate @entries

app/views/entries/show.html.haml
- page_title entry.title

#entries
  .entry.last
    .title
      %h1
        = entry.title
    .date
      = entry.published_at.try(:to_s, :long)
    .content
      ~ entry.body.html_safe

    %a{ :name => 'comments' }
    #comments
      %h2 Comments
      - if entry.comments.any?
        - entry.comments.each do |comment|
          .comment
            - if admin_signed_in?
              .delete
                = link_to image_tag('delete.png'),
                  entry_comment_path(entry, comment),
                  :confirm => 'Are you sure?',
                  :method => :delete
            - if comment.respond_to?(:gravatar_url)
              .gravatar
                = image_tag comment.gravatar_url(:default => default_gravatar_url)
            .author
              = comment.name
              %span.when
                = comment.created_at.to_s(:long)
            .body
              = comment.body.html_safe
      - else
        .comment
          .author
            None yet...

      %a{ :name => 'add-comment' }
      #new_comment
        %h2 Add a comment
        = semantic_form_for [entry, comment] do |form|
          = form.input :name
          = form.input :nickname
          = form.input :email, :label => 'Email (not shown to the public)'
          = form.input :url, :label => 'Website'
          = form.input :body, :label => 'Comment',
            :hint => "Textile enabled (#{link_to 'Reference', 'http://redcloth.org/try-redcloth/', :target => '_blank'})".html_safe
          = form.submit 'Add comment'

app/views/layouts/_flashes.html.haml
- flash.each do |key, value|
  %div{ :class => "flash-#{key}" }
    = value

app/views/layouts/_footer.html.haml
Powered by #{link_to 'JABE', 'http://github.com/pixels-and-bits/jabe'}
a #{link_to 'Pixels and Bits', 'http://pixels-and-bits.com'} project

app/views/layouts/_header.html.haml
%h1#site-title
  = link_to SETTINGS.site_name, '/'
%h1#site-tagline
  = SETTINGS.tagline

app/views/layouts/_sidebar.html.haml
%h2
  = SETTINGS.sidebar_heading

- unless SETTINGS.github_username.blank?
  .link
    = link_to 'Github', SETTINGS.github_username

- unless SETTINGS.twitter_username.blank?
  .link
    = link_to 'Twitter', SETTINGS.twitter_username

- unless SETTINGS.facebook_url.blank?
  .link
    = link_to 'Facebook', SETTINGS.facebook_url

- if SETTINGS.show_github_badge
  #github-badge

  :javascript
    GITHUB_USERNAME="#{SETTINGS.github_username}";
  = javascript_include_tag 'http://drnicjavascript.rubyforge.org/github_badge/dist/github-badge-launcher.js'

app/views/layouts/application.html.haml
<!doctype html>
/[if lt IE 7 ] <html lang="en" class="no-js ie6">
/[if IE 7 ] <html lang="en" class="no-js ie7">
/[if IE 8 ] <html lang="en" class="no-js ie8">
/[if IE 9 ] <html lang="en" class="no-js ie9">
/ [if (gt IE 9)|!(IE)]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
      = "#{@page_title} - " if @page_title
      = SETTINGS.site_name
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    = csrf_meta_tag
    = auto_discovery_link_tag :atom, feed_path
    = stylesheet_link_tag 'boilerplate', 'jabe', 'application'
    = yield :stylesheets
    - if @jabe_stylesheets
      - @jabe_stylesheets.each do |name|
        = stylesheet_link_tag(name)
    = javascript_include_tag 'libs/modernizr-1.6.min.js'
    %script{ :type => 'text/javascript', :charset => 'utf-8' }
      $(document).ready(function() {
      = yield :on_ready
      })
  %body
    #container
      %header
        = render 'layouts/header'
      - if admin_signed_in?
        %nav.nav.admin
          %ul
            %li= link_to 'Entries', admin_entries_path
            %li= link_to 'Settings', edit_admin_settings_path
            %li= link_to 'Logout', destroy_admin_session_path
      #main
        #content
          = render 'layouts/flashes'
          = yield
        #sidebar
          = render 'layouts/sidebar'
      %footer
        = render 'layouts/footer'
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js"}
    :javascript
      !window.jQuery && document.write(unescape('%3Cscript src="/javascripts/libs/jquery-min.js"%3E%3C/script%3E'))
    = javascript_include_tag 'plugins', 'application', 'rails'
    = yield :javascripts
    - if @jabe_javascripts
      - @jabe_javascripts.each do |name|
        = javascript_include_tag(name)

    /[if lt IE 7 ]
      <script src="/javascripts/libs/dd_belatedpng.js"></script>
      <script> DD_belatedPNG.fix('img, .png_bg'); </script>
    - unless Rails.env.production?
      / yui profiler and profileviewer - remove for production
      = javascript_include_tag 'libs/profiling/yahoo-profiling.min.js'
      = javascript_include_tag 'libs/profiling/config.js'
    - unless SETTINGS.google_tracker_id.blank?
      :javascript
        var _gaq = [['_setAccount', '#{SETTINGS.google_tracker_id}'], ['_trackPageview']];
        (function(d, t) {
         var g = d.createElement(t),
             s = d.getElementsByTagName(t)[0];
         g.async = true;
         g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
         s.parentNode.insertBefore(g, s);
        })(document, 'script');